# Machine Learning
## Appliqué à [Gym.OpenAI](https://gym.openai.com)

Parmis les algorithmes de "*machine learning*" (d'apprentissage automatique), on trouve : 
- le Q-Learning
- les algorithmes évolutionnaires (algorithmes génétiques)
- les réseaux de neurones
- ...

Chacun de ces algorithmes suit une trame générale, mais est constament l'objet d'optimisation (choix des valeurs des constantes d'apprentissage, définition d'une fonction objectif, d'une fonction de correction, ...).

Pour comparer différents approches, il est important d'avoir un cadre de référence commun.
[Gym](https://gym.openai.com) est un de ces cadres.




---
## Présentation de Gym

Gym propose un ensemble d'environnement de tests : 
- "Classic control" : problèmes de contrôle classique dans la littérature du ML
- "Algorithms" : problèmes d'imitation du calcul (apprendre l'addition par exemple)
- "Box2D" : exercice de contrôle continu sur un environnement 2D
- "MuJoCo" : contrôle continu d'un robot 3D pour apprendre à se déplacer
- "Robotics" : contrôle d'un automate (machine outil)
- "Toy text" : exemple réduit affichés en mode texte
- plus des environnements plugables (jeux atari, .....)


### Installation de gym

#### Outil AUTRE QUE COLAB (pyzo, jupyter lab, .....)

In [ ]:
!pip install gym

In [8]:
import gym

#### <font color=red>Sous colab</font>
*Sous colab, l'affichage ne sera pas dynamique.. Il faudra passer soit par un rendu sous forme de plot (matplotlib), soit passer par une vidéo à enregistrer...*

***Solution pour affichage statique***<br>
*Il vous faut importer, seulement si vous utilisez colab, les packages suivants :*

In [ ]:
!apt-get install -y xvfb python-opengl > /dev/null 2>&1
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!apt-get install x11-utils

In [ ]:
import gym
import numpy as np
import matplotlib.pyplot as plt
from IPython import display as ipythondisplay
from pyvirtualdisplay import Display
display = Display(visible=0, size=(400, 300))
display.start()

---
### Charger un environnement
Un environnement se charge par la commande : `env = gym.make('nomenvironnement')`

In [9]:
#exemple : 
env = gym.make('MountainCarContinuous-v0') 
env.reset()

/Users/emmanueladam/opt/anaconda3/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


array([-0.41415622,  0.        ])

---
### Afficher un environnement
#### Outil AUTRE QUE COLAB (pyzo, jupyter lab, .....)
affichage de l'état actuel de l'environnement :

In [10]:
env.render()

True

#### <font color=red>Afficher sous colab</font>
*utilisation d'un plot (matplotlib), soit passer par une vidéo à enregistrer...*


In [ ]:
rendu = env.render(mode='rgb_array')
plt.imshow(rendu)

---
### Les types d'environnements
Un environnement peut être 
- discret : les actions à entreprendre sont discrete (avancer, reculer, ...)
- continu : les actions à entreprendre dépendent de valeurs réelles

Un environnement est borné, et l'objet à mouvoir l'est également.
- **accéder aux caracteristiques** : `env.spec`
- **les actions possibles** : `env.action_space`
- **le nombre de valeurs observables** : `env.observation_space`
- **le domaine de valeurs (si réelles)** : `env.observation_space.high` et `env.observation_space.low`

In [11]:
print(env.spec)
print("nombre et type d'actions = ", env.action_space) 
print("valeurs d'actions les plus elevées = ", env.action_space.high) # seulement si box (non discret)
print("valeurs d'actions les plus basses = ", env.action_space.low)  # seulement si box (non discret)
print("nombre et type d'observations = ", env.observation_space) 
print("valeurs de observations les plus elevées = ", env.observation_space.high) # seulement si box (non discret)
print("valeurs de  observations les plus basses = ", env.observation_space.low) # seulement si box (non discret)

EnvSpec(MountainCarContinuous-v0)
nombre et type d'actions =  Box(1,)
valeurs d'actions les plus elevées =  [1.]
valeurs d'actions les plus basses =  [-1.]
nombre et type d'observations =  Box(2,)
valeurs de observations les plus elevées =  [0.6  0.07]
valeurs de  observations les plus basses =  [-1.2  -0.07]


In [14]:
# exemple avec un autre environnement : 
env = gym.make('MountainCar-v0') 
env.reset()
print(env.spec)
print("nombre et type d'actions = ", env.action_space) 


EnvSpec(MountainCar-v0)
nombre et type d'actions =  Discrete(3)


### Les types de valeurs
- `Discrete(3)`: signifie que la variables est discrete et prend ses valeurs dans 0,1,2
- `Box(1,)`: signifie que la variable est un tableau contenant 1 réel

---
### Comprendre les valeurs des caractéristiques et des actions
Se référer à la documentation pour comprendre les actions..<br>
Par exemple, pour `MountainCarContinuous-v0`, vous trouverez l'explication des valeurs [ici](https://github.com/openai/gym/wiki/MountainCarContinuous-v0).

| No | Observation | Min | Max |
|:--:|:--:|:--:|:--:|
| 0 | Position | -1.2 | 0.6 |
| 1 | Velocité | -0.07 | 0.07 |

On peut donc récupérer la position x de la voiture et sa vitesse.

---
### Les actions
Se référer à la documentation pour comprendre les actions..<br>
Exemple :
- Dans `MountainCar-v0` : 0 fait reculer le véhicule, 1 le met au point mort, 2 le fait avancer
- Dans `MountainCarContinuous-v0` : [-1.0] fait reculer le véhicule d'une force 1, [0] le met au point mort, [1.0] le fait avancer d'une force 1

- ***Exécuter une action :***
  - *choix aléatoire* : `action = env.action_space.sample()`
  - *exécution* : `observation, reward,done,info = env.step(action)`
    - `observation`: selon l'environnement, pour moutain car, la position du mobile et sa vitesse ([x, v])
    - `reward`: utilité de l'état (récompense)
    - `done` : booléen (True si but atteint)
    - `info` : éventuelle information retournée par l'outil


In [15]:
action = env.action_space.sample()
observation, reward,done,info = env.step(action)
#sous outil autre que Colab : 
env.render()

True

In [16]:
print ("apres execution de ", action)
print (observation, reward, done, info)

apres execution de  2
[-0.56969574  0.00135469] -1.0 False {}


---
### La récompense (reward)
Le *reward* dépend l'environnement d'exécution.. Dans `MountainCarContinuous-v0`, il est de `100(si le but est atteint) - le nombre d'actions au carré` !!
Selon la méthode IA choisie, il peut être plus intéressant de définir sa popre fonction récompense 
(par exemple, on peut favoriser les séquences qui mène le plus loin possible..)


---
### Exemple d'exécution
*Sous outil autre que Colab*, 
le code suivant effectue 100 actions aléatoire, et demande le rendu à chaque étape 

In [7]:
def hasard():
    env.reset()
    for step in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Objectif atteint par hasard apres {} actions".format(step+1))
            break
hasard()

***Sous Colab***, on affiche le rendu qu'une fois toutes les actions effectuées : 


In [ ]:
def hasard_colab():
    env.reset()
    for step in range(100):
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Objectif atteint par hasard apres {} actions".format(step+1))
            break
    rendu = env.render(mode='rgb_array')
    plt.imshow(rendu)

hasard_colab()

---
### Aide python
Quelques éléments python pour faciliter la programmation d'un IA basée sur une liste d'exemples ou de tests.<br>
***Listes***

In [8]:
#liste en python = ensemble de valeurs de types différents ou non : 
t = [[[-1.0],[0.5],[1.0],[0.0]], 0.5]
print(t[0])
print(t[1])

[[-1.0], [0.5], [1.0], [0.0]]
0.5


In [9]:
#ajout d'un element : 
t.append([1,2,3])
print(t)

[[[-1.0], [0.5], [1.0], [0.0]], 0.5, [1, 2, 3]]


In [10]:
#longueur d'une liste
print(len(t))

3


In [11]:
#tri
liste = [3,5,2,1]
print(liste)
liste.sort()
print(liste)

[3, 5, 2, 1]
[1, 2, 3, 5]


In [5]:
import numpy as np
#comparateur "à la java"
import functools

###compare 2 tuples sur base du 2e element. 
### retourne <0 si tupleB[1] < tupleA[1]
### retourne >0 si tupleB[1] > tupleA[1]
### retourne 0  si tupleB[1] = tupleA[1]
def comp(tupleA, tupleB)->int:
    return (int(round(tupleB[1]*100)) - int(round(tupleA[1]*100)))

liste = [
[np.array([ 0,  1,  1]),  -0.72],
[np.array([-1,  0,  1]),  -0.73],
[np.array([-1,  0, -1]),  -0.24],
[np.array([ 0,  0, -1]),  0.70],
[np.array([ 0, -1,  1]),  -0.77],
[np.array([-1, -1,  1]),  0.31]]
print(liste)
print("----")
liste_triee = sorted(liste, key=functools.cmp_to_key(comp))
print(liste_triee)   

[[array([0, 1, 1]), -0.72], [array([-1,  0,  1]), -0.73], [array([-1,  0, -1]), -0.24], [array([ 0,  0, -1]), 0.7], [array([ 0, -1,  1]), -0.77], [array([-1, -1,  1]), 0.31]]
----
[[array([ 0,  0, -1]), 0.7], [array([-1, -1,  1]), 0.31], [array([-1,  0, -1]), -0.24], [array([0, 1, 1]), -0.72], [array([-1,  0,  1]), -0.73], [array([ 0, -1,  1]), -0.77]]


***Tableaux***<br>
Utilisation de la classe numpy

In [4]:
import numpy as np
#creation de tableaux
tab0 = np.zeros((10), int)
print(tab0)
mat = np.zeros((2,3), float)
print(mat)
#avec passage de valeurs
tab_val = np.array([1,2,3,4])
print(tab_val)

[0 0 0 0 0 0 0 0 0 0]
[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#génération de valeurs aléatoires
#création d'une matrice 2x3 avec valeurs entières entre -1 et 1 (2 exclus)
mat1 = np.random.randint(-1, 2, (2,3)) 
print(mat1)
print()
#création d'une matrice 4x2 avec valeurs réelles  entre 0 et 1
mat2 = np.random.random((4,2)) 
print(mat2)
print()
#création d'une matrice 3x3 avec valeurs réelles  entre 0 et 100
mat3 = np.random.random((3,3)) * 100
print(mat3)
print()

[[0 1 1]
 [0 0 0]]

[[0.98588534 0.98334186]
 [0.82152201 0.07289338]
 [0.70669319 0.85179551]
 [0.6014171  0.48856643]]

[[20.99603294 20.75133941 13.48394904]
 [11.15488157 59.55780718 32.71681798]
 [63.42948124 67.29256084 13.01564832]]



In [14]:
#extraits de tableau
tab1 = np.array([1,2,3,4,5,6])
tab1_partA = tab1[:3]
tab1_partB = tab1[3:]
print (tab1_partA)
print (tab1_partB)

[1 2 3]
[4 5 6]


In [15]:
#concaténation de tableaux
tab2 = np.array([10,20,30,40,50,60])
tab2_partB = tab2[3:]
mixe = np.concatenate((tab1_partA, tab2_partB))
print (mixe)

[ 1  2  3 40 50 60]


In [16]:
#egalite entre tableaux
tab3 = np.array([1,2,3,4,5,7])
print(np.array_equal(tab1, tab3))
print(np.array_equal(tab1, tab1))

False
True
