<a href="https://colab.research.google.com/github/EmmanuelADAM/IntelligenceArtificiellePython/blob/master/TPMLGymQLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning
## Appliqué à [Gym.OpenAI](https://gym.openai.com)

---
## Présentation de Gym

Voir la page d'introduction à [Gym](https://gym.openai.com).

### Installation de gym

#### Outil AUTRE QUE COLAB (pyzo, jupyter lab, .....)

In [ ]:
!pip install gym

In [2]:
import gym

---
## Test de ML par Q-Learning pour atteindre l'objectif
- Utiliser l'environnement `FrozenLake8x8-v0` (un labyrinthe en mode texte)
- 4 actions sont possibles (Left(0), Down(1), Right(2), Up(3))
  - l'adjectif "Frozen" signifie qu'une *action n'est pas déterministe !*
    - à partir d'une case "gelée", aller à droite peut .. mener à droite, ou pas
    - => intérêt du Q-Learning adapté à ce type d'environnement probabiliste
- Le labyrinthe est ainsi composé de zones glacées, de puits, et d'un objectif

En vous basant sur les codes présent dans l'article [Q-Learning en Java](http://emmanuel.adam.free.fr/site/spip.php?article134), programmer un algo de Q-Learning pour apprendre à atteindre l'objectif 

**N.B.** 
  - *Cet environnement fonctionne bien sous colab, jupyterlab.. quelques soucis de l'affichage de l'état courant (carré rouge) sous Pyzo....* 
  - Il est fortement conseillé de débuter avec un environnement déterministe pour évaluer la bonne marche de l'algo de Q-Learning que vous aurez développer..
    - pour cela, lancer l'environnement avec 

---
#### Etude de l'environnement

In [3]:
env = gym.make('FrozenLake-v0') # tester FrozenLake8x8 pour l'environnement plus large
print(env.spec)
print(env.action_space) #ici 4 actions discrétisée
print(env.observation_space) # ici 4x4 cellules possibles

env.reset()
env.render()
print("S = Start, G = Goal, H = Hole, F = Frozen place")

EnvSpec(FrozenLake-v0)
Discrete(4)
Discrete(16)

SFFF
FHFH
FFFH
HFFG
S = Start, G = Goal, H = Hole, F = Frozen place


---
#### Test des actions

In [4]:
###### Test des fonctions
env.reset()
action = 0
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)

  (Left)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 0 ,gain: 0.0 ,fini: False , {'prob': 0.3333333333333333}


In [5]:
env.reset()
action = 1
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)

  (Down)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 4 ,gain: 0.0 ,fini: False , {'prob': 0.3333333333333333}


In [6]:
env.reset()
action = 2
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)

  (Right)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 4 ,gain: 0.0 ,fini: False , {'prob': 0.3333333333333333}


In [7]:
env.reset()
action = 3
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)

  (Up)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 1 ,gain: 0.0 ,fini: False , {'prob': 0.3333333333333333}


In [8]:
#note : 
## observation = position où se trouve l'agent
## reward = recompense
## done = but atteint
## info = proba de reussite de l'action

On est clairement ici dans un environnement non déterministe (une même action à partir d'un même état ne mène pas toujours au même résultat); c'est le contexte de prédilection de l'algo de Q-Learning...

---
### <font color="red">Mise en place de l'environnement en mode déterministe</font>
Important, pour valider l'apprentissage de votre algorithme avant de passer en mode non-déterministe, il vaut mieux le tester sur un environnement où chaque action à 100% de réussite. Ci-dessous un exemple sur le mini labyrinthe.

In [9]:
env = gym.make('FrozenLake-v0', is_slippery=False)
env.reset()
action = 2
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)
action = 2
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)
action = 1
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)
action = 1
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)
action = 1
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)
action = 2
observation, reward, done, info = env.step(action)
env.render()
print("pos° actuelle:", observation,",gain:", reward,",fini:", done,",", info)


  (Right)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 1 ,gain: 0.0 ,fini: False , {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 2 ,gain: 0.0 ,fini: False , {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 6 ,gain: 0.0 ,fini: False , {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 10 ,gain: 0.0 ,fini: False , {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 14 ,gain: 0.0 ,fini: False , {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
pos° actuelle: 15 ,gain: 1.0 ,fini: True , {'prob': 1.0}


---
***Aide Python : (plusieurs possibilités)***
- Il n'est pas nécessaire de créer des classes Etat, ....
- Il faut pouvoir stocker les récompenses de chaque actions à partir de chaque case
  - a priori, la création d'une matrice 4x4 de 4 valeurs peut être utile.
  Plus simplement, on utilisera un tableau de n cases (pour les n etats) contenant m valeurs d'actions 
  

In [10]:
import numpy as np
# cree un tableau de n cases x m actions
q_actions = np.zeros((env.observation_space.n, env.action_space.n), np.float32)
print(q_actions)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


*Recherche du max et de sa position*

Reprenons la derniere modélisation sous forme de tableau de 4 valeurs.

In [54]:
#Exemple de recherche..
#1. ici pour l'exemple, on place des valeurs aléatoires pour les actions
Q = np.random.random((env.observation_space.n, env.action_space.n))
print(Q)

[[0.2066786  0.09571378 0.51688347 0.05415255]
 [0.75066335 0.74831572 0.06387416 0.84854258]
 [0.83406533 0.80558654 0.22978986 0.23528311]
 [0.44997395 0.66794793 0.61921367 0.48222429]
 [0.85204815 0.30694744 0.78731277 0.11334462]
 [0.2733148  0.79489722 0.83269927 0.4747544 ]
 [0.93406451 0.28838276 0.59015805 0.67367305]
 [0.18213117 0.95138439 0.40462532 0.84738508]
 [0.48898813 0.55316361 0.5107132  0.11692906]
 [0.21276702 0.26798434 0.65192879 0.76056712]
 [0.86129877 0.10571659 0.02035535 0.29236254]
 [0.25580737 0.99092468 0.69634389 0.58834477]
 [0.02926987 0.76848053 0.7319501  0.62312869]
 [0.22711828 0.77157755 0.81645795 0.35623859]
 [0.68139813 0.87213529 0.37016551 0.89845041]
 [0.64915572 0.64189817 0.70991113 0.71377006]
 [0.76090114 0.45779089 0.28186897 0.97592355]
 [0.20407737 0.23451658 0.99375917 0.12687101]
 [0.95511916 0.70910822 0.41400826 0.70365044]
 [0.05508487 0.32477776 0.24022979 0.61247974]
 [0.98278188 0.47244426 0.31157547 0.1859517 ]
 [0.34801596 

In [55]:
#max de la case 2
max_2 = np.max(Q[2, :])
position_max_2 = np.argmax(Q[2,:])
print("case 2, max=",max_2, ", en position ", position_max_2)
print("la meilleure action de l'etat 2 serait donc ", position_max_2)

case 2, max= 0.8340653280315182 , en position  0
la meilleure action de l'etat 2 serait donc  0
